-- Minimal Hyprland config for the greetd greeter session only.
-- Not the user's real hyprland.lua - this just hosts hyprlogin so it gets
-- real per-monitor wlr-layer-shell surfaces (unlike cage), which is what
-- gives it the same monitor-mirroring behaviour as hyprlock.

hl.config({
    autogenerated = false,
})

hl.config({
    animations = { enabled = false },
    decoration = {
        rounding = 0,
        blur = { enabled = false },
    },
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 0,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "rgb(000000)",
        disable_watchdog_warning = true,
    },
    input = {
        kb_layout = "us",
    },
})

hl.exec_once("hyprlogin")
