wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/dachshund.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/Pictures/wallpapers/dachshund.png
    fit_mode = cover
}

splash = false
ipc = on
