input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    mouse_refocus = true
    sensitivity = -0.5

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        scroll_factor = 0.8
    }

    numlock_by_default = true
}

gesture = 3, horizontal, workspace

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    focus_preferred_method = 0
}
