monitor = desc:eDP-1, disable

monitor = DP-6, 2560x1440@200.01, 1920x0, 1, vrr, 0
monitor = DP-5, 1920x1080@179.96, 0x500, 1

workspace = 1, monitor:DP-6, default:true
workspace = 2, monitor:DP-6
workspace = 3, monitor:DP-6
workspace = 4, monitor:DP-6
workspace = 5, monitor:DP-6
workspace = 6, monitor:DP-5, default:true
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-5
workspace = 9, monitor:DP-5
workspace = 10, monitor:DP-5
