windowrule = float on, match:class pavucontrol
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class org.gnome.Calculator
windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class zenity
windowrule = float on, match:class swappy
windowrule = float on, match:class hotkeys-menu
windowrule = size 55% 70%, match:class hotkeys-menu
windowrule = center 1, match:class hotkeys-menu

windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = size 25% 25%, match:title ^(Picture-in-Picture)$
windowrule = move 73% 71%, match:title ^(Picture-in-Picture)$

windowrule = no_anim on, match:workspace special:minimized

layerrule {
    name = control_center_popover
    match:namespace = control-center
    blur = false
    animation = popin 80%
}

windowrule = opacity 0.94 0.88, match:class kitty
windowrule = opacity 0.94 0.88, match:class yazi-fm
windowrule = opacity 0.96 0.9, match:class hotkeys-menu
windowrule = rounding 10, match:class hotkeys-menu
windowrule = rounding 10, match:class yazi-fm
windowrule = opacity 0.97 0.9, match:class firefox

windowrule = suppress_event maximize, match:class .*
