background            #181310
foreground            #d3b9a1
background_opacity    0.88
background_blur       40

active_border_color   #c9702f
inactive_border_color #473228

cursor             #d3b9a1
cursor_text_color  #181310
cursor_shape       beam
cursor_beam_thickness 1.5

color0  #201a16
color8  #72553e
color1  #db765c
color9  #ed896a
color2  #bca460
color10 #d2be81
color3  #e39b65
color11 #f3b174
color4  #ba916d
color12 #cbaa88
color5  #c58893
color13 #dc9faa
color6  #9aac98
color14 #accaa9
color7  #c0a38c
color15 #e7dac6
