background            #110d17
foreground            #d9ccec
background_opacity    0.88
background_blur       40

active_border_color   #a987e8
inactive_border_color #3a2d4f

cursor             #d9ccec
cursor_text_color  #110d17
cursor_shape       beam
cursor_beam_thickness 1.5

color0  #17121f
color8  #6a5790
color1  #e8708e
color9  #f590a9
color2  #9ccf9a
color10 #b5e0b2
color3  #ecc57c
color11 #f5d59c
color4  #8aa2ee
color12 #a9bcf7
color5  #c38ff0
color13 #d9aefb
color6  #86d0d6
color14 #a8e2e6
color7  #c2b2da
color15 #f0eafa
