player: "mpris"
ignoreErrors: true
timerInterval: 200
updateInterval: 500

omitTitle: false
centerLyrics: true

style:
  hAlignment: center
  lineHeight: 2

  before:
    foreground: "#6b4526"
    faint: true
    bold: false

  current:
    foreground: "#f5dcb8"
    background: ""
    bold: true
    italic: false

  after:
    foreground: "#8a6650"
    faint: true

pipe:
  length: 0
  overflow: word

mpris:
  players: ["chromium", "cider"]
